USE Sistema_Empleados;
GO

-------LISTAR-------
CREATE OR ALTER PROC SP_LISTAR_USUARIO
AS
BEGIN
    BEGIN TRY
        SELECT NOMBRE_USUARIO , CONTRASEÑA , ACTIVO
        FROM TBL_USUARIOS as PROV
    END TRY
    BEGIN CATCH
        PRINT 'NO SE LISTO LOS USUARIO , VERIFICA EL ERROR: ' + @@error
    END CATCH
END
GO

-----------------INSERTAR----------------
CREATE OR ALTER PROC SP_INSERTAR_USUARIO
(
	@NOMBRE_USUARIO VARCHAR (100),
	@CONTRASEÑA VARCHAR (100),
	@ACTIVO BIT 
)
AS
BEGIN
  BEGIN TRY
    BEGIN TRAN
        INSERT INTO TBL_USUARIOS
        (NOMBRE_USUARIO , CONTRASEÑA ,ACTIVO) VALUES
        (@NOMBRE_USUARIO , @CONTRASEÑA , @ACTIVO)
    COMMIT
    PRINT 'USUARIO INSERTADO CORRECTAMENTE'
  END TRY
  BEGIN CATCH
    ROLLBACK
    PRINT 'NO SE INSERTO EL USUARIO POR EL ERROR, VERIFICA: ' + CAST(ERROR_NUMBER() AS VARCHAR)
  END CATCH    
END
GO


EXEC SP_INSERTAR_USUARIO 
    @NOMBRE_USUARIO = 'admin',
    @CONTRASEÑA = '12345',
    @ACTIVO = 1;


-----------------EDITAR--------------

CREATE OR ALTER PROC SP_EDITAR_USUARIO
(
	@ID_USUARIO INT,
	@NOMBRE_USUARIO VARCHAR (100),
	@CONTRASEÑA VARCHAR (100),
	@ACTIVO BIT 
)

AS
BEGIN
    BEGIN TRY
        BEGIN TRAN
        update TBL_USUARIOS 
        SET NOMBRE_USUARIO = @NOMBRE_USUARIO,
			CONTRASEÑA = @CONTRASEÑA,
			ACTIVO = @ACTIVO
            
            WHERE ID_USUARIO = @ID_USUARIO
        COMMIT
        PRINT 'EL USUARIO SE EDITO CORRECTAMENTE'
    END TRY
    BEGIN CATCH
    ROLLBACK
    PRINT 'NO SE EDITO EL USUARIO POR EL ERROR:' + @@ERROR
    END CATCH
END
GO

EXEC SP_EDITAR_USUARIO 
    @ID_USUARIO = 3,
    @NOMBRE_USUARIO = 'LizM',
    @CONTRASEÑA = 'Pass2025',
    @ACTIVO = 0;


--------ELIMINAR-----------------

CREATE OR ALTER PROC SP_ELIMINAR_USUARIO
(
	@ID_USUARIO INT
)
AS
BEGIN
    BEGIN TRY
    BEGIN TRAN
    DELETE TBL_USUARIOS WHERE ID_USUARIO = @ID_USUARIO
    COMMIT
    PRINT 'SE ELIMINO CORRECTAMENTE EL USUARIO'
    END TRY
    BEGIN CATCH
    ROLLBACK
    PRINT 'NO SE ELIMINO EL USUARIO POR EL ERROR:' + @@ERROR
    END CATCH
END
GO

EXEC SP_ELIMINAR_USUARIO
    @ID_USUARIO = 3;